import React, { createContext } from 'react'

export const projectContext = createContext()

const ProjectContext = ({ children }) => {

  const projectData = [
    {
      projectname: "nexpoze production",
      serviceprovided: "Brand Development, Portfolio Management, Social Media Marketing, Dynamic Presentations, Video/Photo Editing",
      para1: "Nexpoze Production, a studio dedicated to capturing memories and crafting stunning visuals, partnered with us to elevate their digital presence and redefine their brand identity. We meticulously worked on positioning Nexpoze as the go-to destination for premium photography and videography services.",
      para2: "Our approach included creating a cohesive brand strategy that emphasized their creativity and attention to detail. We designed a content calendar filled with engaging posts, behind-the-scenes footage, and portfolio highlights, showcasing their expertise in delivering exceptional results.",
      coverimage1: "/images/nexpoze-cover1.png",
      coverimage2: "/images/nexpoze-cover2.png",
      image3: "/images/nexpoze-image3.png",
      image4: "/images/nexpoze-image4.png",
      image5: "/images/nexpoze-image5.png",
      image6: "/images/nexpoze-image6.png",
      image7: "/images/nexpoze-image7.png",
      image8: "/images/nexpoze-image8.png",
      image9: "/images/nexpoze-image9.png",
      portraitVideo: "/videos/nexpoze.mp4",
    },
    {
      projectname: "daroma – an italian cafe",
      serviceprovided: "Social Media Management, Brand Strategy, Video/Photo Shoot, Reels, Content Creation",
      para1: "At Daroma, an Italian café inspired by the rich culinary and cultural traditions of Italy, we embarked on a journey to elevate their brand presence and resonate with their audience. By immersing ourselves in Daroma’s unique identity, we crafted a digital strategy that celebrated their love for authentic flavors and cozy ambiance.",
      para2: "From curating aesthetically pleasing visuals to producing engaging video content and reels, we brought Daroma's story to life on digital platforms. Our social media management ensured consistent branding, while targeted campaigns effectively drove engagement and footfall to the café.",
      coverimage1: "/images/daroma-cover1.png",
      coverimage2: "/images/daroma-cover2.png",
      image3: "/images/daroma-image3.png",
      image4: "/images/daroma-image4.png",
      image5: "/images/daroma-image5.png",
      image6: "/images/daroma-image6.png",
      image7: "/images/daroma-image7.png",
      image8: "/images/daroma-image8.png",
      image9: "/images/daroma-image9.png",
      portraitVideo: "/videos/Daroma.mp4",

    },
    {
      projectname: "envision dazzling",
      serviceprovided: "event management, branding, digital marketing",
      para1: "Wineemedia played a crucial role in helping Envision Dazzling organize their event, ensuring every detail was meticulously planned and executed for a seamless experience. Our team not only managed the event logistics but also handled the branding and digital marketing, creating a cohesive and visually appealing brand presence.",
      para2: "By crafting engaging promotional content and leveraging digital platforms, we successfully boosted event visibility and engagement. This comprehensive support helped Envision Dazzling deliver a memorable event, strengthening their brand and expanding their reach.",
      coverimage1: "/images/envision-cover1.png",
      coverimage2: "/images/envision-cover2.png",
      image3: "/images/envision-image3.png",
      image4: "/images/envision-image4.png",
      image5: "/images/envision-image5.png",
      image6: "/images/envision-image6.png",
      image7: "/images/envision-image7.png",
      landScapeVideo: "/videos/envision.mp4",
    },
    {
      projectname: "zerror studios",
      serviceprovided: "video graphics, logo animation",
      para1: "We were instrumental in helping Zerror deliver a top-notch video for their client, Reside In Being. Our exceptional video production skills ensured a polished and engaging final product that perfectly encapsulated the client's vision. Additionally, we crafted a dynamic logo animation for Zerror, enhancing their brand identity and professional appeal.",
      para2: " This seamless blend of high-quality video content and eye-catching logo animation significantly elevated Zerror's service offering, impressing their client and strengthening their market position.",
      coverimage1: "/images/zerror-cover1.png",
      coverimage2: "/images/zerror-cover2.png",
      image3: "/images/zerror-image3.png",
      image4: "/images/zerror-image4.png",
      image5: "/images/zerror-image5.png",
      image6: "/images/zerror-image6.png",
      image7: "/images/zerror-image3.png",
      portraitVideo: "/videos/Zerror.mp4",
    },
    {
      projectname: "pepe cafe",
      serviceprovided: "social media management, video/photo shoot, reels",
      para1: "With our tailored approaches, we worked closely with Pepe Cafe to develop a comprehensive strategy that aligned with their brand identity and business goals. From creating engaging content to implementing effective advertising campaigns, we utilized our expertise to build a vibrant online community around Pepe Cafe.",
      para2: "Through captivating visuals, compelling storytelling, and strategic engagement tactics, we helped Pepe Cafe connect with their audience, increase brand awareness, and drive customer engagement. It's been a pleasure to partner with Pepe Cafe on their digital journey, and we look forward to continuing to support their success in the future",
      coverimage1: "/images/Pe-cover1.png",
      coverimage2: "/images/Pe-cover2.png",
      image3: "/images/Pe-image3.png",
      image4: "/images/Pe-image4.png",
      image5: "/images/Pe-image5.png",
      image6: "/images/Pe-image6.png",
      image7: "/images/Pe-image7.png",
      image8: "/images/Pe-image8.png",
      image9: "/images/Pe-image9.png",
      portraitVideo: "/videos/pepe.mp4",
    },
    {
      projectname: "pace entertainment",
      serviceprovided: "social media management, video/photo shoot, reels",
      para1: "With our tailored approaches, we worked closely with Pepe Cafe to develop a comprehensive strategy that aligned with their brand identity and business goals. From creating engaging content to implementing effective advertising campaigns, we utilized our expertise to build a vibrant online community around Pepe Cafe.",
      para2: "Through captivating visuals, compelling storytelling, and strategic engagement tactics, we helped Pepe Cafe connect with their audience, increase brand awareness, and drive customer engagement. It's been a pleasure to partner with Pepe Cafe on their digital journey, and we look forward to continuing to support their success in the future",
      coverimage1: "/images/pace-cover1.png",
      coverimage2: "/images/pace-cover2.jpg",
      image3: "/images/pace-image3.jpg",
      image4: "/images/pace-image4.jpg",
      image5: "/images/pace-image5.png",
      image6: "/images/pace-image6.png",
      image7: "/images/pace-image7.png",
      image8: "/images/pace-image8.jpg",
      image9: "/images/pace-image9.png",
      portraitVideo: "/videos/paceE.mp4",

    },
    {
      projectname: "maab cosmetics",
      serviceprovided: "graphic posts, social media management",
      para1: "Leveraging our expertise in design and social media management, we seamlessly integrated MA’AB Cosmetics' which is one of the leading destinations for skin, laser and hair treatment, to build and identity treatment offerings into captivating visuals that resonate with their audience. ",
      para2: "Our strategic approach ensured that each graphic post not only showcased MA’AB Cosmetics' expertise but also conveyed their commitment to enhancing beauty and confidence. We're proud to have played a part in elevating MA’AB Cosmetics' digital presence and look forward to continued success together.",
      coverimage1: "/images/maab-cover1.png",
      coverimage2: "/images/maab-cover2.png",
      image3: "/images/maab-image3.png",
      image4: "/images/maab-image4.png",
      image5: "/images/maab-image5.png",
      image6: "/images/maab-image6.png",
      image7: "/images/maab-image7.png",
      image8: "/images/maab-image8.png",
      image9: "/images/maab-image9.png",
    },
    {
      projectname: "pace premium",
      serviceprovided: "graphics, creatives",
      para1: "By understanding Pace Premium's unique identity, Wineemedia created visually stunning and cohesive graphics that enhanced the brand's appeal, effectively capturing the elegance and exclusivity of its luxury footwear.",
      para2: " This collaboration significantly boosted Pace Premium's market presence and engagement with discerning customers.",
      coverimage1: "/images/pacep-cover1.png",
      coverimage2: "/images/pacep-cover2.png",
      image3: "/images/pacep-image3.png",
      image4: "/images/pacep-image4.png",
      image5: "/images/pacep-image5.png",
      image6: "/images/pacep-image6.png",
      image7: "/images/pacep-image7.png",
      // image8: "/images/pacep-image8.png",
    },
    {
      projectname: "dawn knight",
      serviceprovided: "videography, video editing",
      para1: "We assisted Dawn Knight in executing a spectacular shoot for their latest PC model, bringing out the best features and design elements through expert photography and videography. Our team ensured every shot was meticulously planned and captured, highlighting the PC model's cutting-edge technology and sleek aesthetics.",
      para2: "Additionally, we created a captivating video edit that seamlessly integrated these visuals with dynamic effects and engaging narrative elements. This comprehensive approach not only showcased Dawn Knight's product in the best light but also enhanced their promotional efforts and market appeal.",
      coverimage1: "/images/dawn-cover1.png",
      coverimage2: "/images/dawn-cover2.png",
      image3: "/images/dawn-image3.png",
      image4: "/images/dawn-image4.png",
      image5: "/images/dawn-image5.png",
      image6: "/images/dawn-image6.png",
      image7: "/images/dawn-image7.png",
      portraitVideo: "/videos/dawn.mp4",
    },

  ];




  return (
    <projectContext.Provider value={projectData}>{children}</projectContext.Provider>
  )
}

export default ProjectContext